#!/usr/bin/env node
// BrewSite documentation MCP server entry point.
// This file is auto-generated by @brewsite/claude-author init.
// It starts the pre-built MCP server from the installed package.
//
// In a monorepo workspace the package may not be hoisted to the root
// node_modules, so we resolve via a direct relative path as a fallback.
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { existsSync } from 'node:fs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Try the direct path first (monorepo workspace), then fall back to the package import.
const localServer = resolve(__dirname, '..', '..', 'packages', 'claude-author', 'dist', 'server.js');
if (existsSync(localServer)) {
  import(localServer);
} else {
  import('@brewsite/claude-author/server');
}
