#!/usr/bin/env node
// BrewSite documentation MCP server entry point.
// This file is auto-generated by @brewsite/claude-author init.
// It starts the pre-built MCP server from the installed package.
import('@brewsite/claude-author/server');
