// darkGlass DiagramTheme preset — obsidian/burgundy control-room look with ember accents.

import type { DiagramTheme } from '@brewsite/diagram';

export const darkGlassTheme: DiagramTheme = {
  node: {
    defaultColor: '#1E1412',
    defaultBoxColor: '#372620',
    defaultMetalness: 0.64,
    defaultRoughness: 0.28,
    nodeEnvMapIntensity: 0.12,
    defaultEmissiveIntensity: 0.07,
    defaultThickness: '4u',
    cornerRadius: '0.9%',
    glowIntensity: 0.10,
    defaultLabelColor: '#F2E6DE',
    defaultSublabelColor: '#B79B8F',
    labelSizeFactor: 1.0,
    sublabelSizeFactor: 1.0,
    defaultIconStyle: 'extruded',
    defaultSize: ['10u', '10u'],
    defaultIconScale: 0.6,
    defaultIconDepth: '3u',
    glowSpread: 2.2,
    defaultBorderColor: '#785e57',
    defaultNodeBorderWidth: '.7u',
    defaultNodeBorderHeight: '.7u',
    labelFontSizeBase: 0.32,
    sublabelFontSizeBase: 0.22,
    defaultLabelPadding: 0,
  },
  edge: {
    defaultColor: '#B33A2B',
    defaultFlowColor: '#E36A2E',
    defaultFlowSpeed: 0.30,
    defaultFlowWidth: 0.20,
    defaultThickness: '.7u',
    defaultMetalness: 0.46,
    defaultRoughness: 0.34,
    routing: 'flow',
    landing: 'nearest-face',
    smoothness: 1.4,
    use3DArrows: true,
    tubeRadialSegments: 14,
    organicVariation: 1.4,
    flowTurnRadius: '3.5%',
    flowFaceStub: '5%',
    flowBundleStrength: 0.9,
    flowObstaclePadding: '2.5%',
    flowTargetApproachBias: 1.35,
    flowTurnPenalty: 0.45,
    flowPunchthroughPenalty: 500,
    flowPulseIntensity: 0.68,
  },
  group: {
    defaultColor: '#160f0d',
    defaultBorderColor: '#6B4338',
    defaultBorderWidth: '1.5u',
    defaultBorderHeight: '4u',
    defaultFillOpacity: 0.11,
    defaultBorderOpacity: 0.85,
    defaultLabelColor: '#F2E6DE',
    borderMetalness: 0.32,
    borderRoughness: 0.48,
    borderSideDarken: 0.42,
    borderEdgeDarken: 0.46,
    defaultBackColor: '#1A1210CC',
  },
  environment: {
    envMapUrl: 'none',
    envMapIntensity: 0.85,
    skyColor: '#100A09',
    horizonColor: '#2A1B18',
  },
  layout: {
    defaultKind: 'grid',
    grid: {
      columns: 'auto',
      spacing: ['4%', '4%'],
      margin: 0,
      groupPadding: '3.5%',
      titleGap: '3%',
      alignment: 'left',
      disconnected: 'next-to',
    },
    hierarchical: {
      direction: 'top-down',
      spacing: ['4.5%', '4.5%'],
      margin: 0,
      groupPadding: '3.5%',
      titleGap: '3%',
      alignment: 'center',
      disconnected: 'next-to',
    },
    manual: {
      groupPadding: '3.5%',
      titleGap: '3%',
    },
  },
  palette: ['#B33A2B', '#E36A2E', '#7A1F2D', '#2E4F7A', '#5A2C1D', '#FF8A3D', '#8F3B4A', '#1E3554'],
} as const;
