// lightCanvas DiagramTheme preset — premium editorial light mode with controlled jewel accents.

import type { DiagramTheme } from '@brewsite/diagram';

export const lightCanvasTheme: DiagramTheme = {
  node: {
    defaultColor: '#FFFFFF',
    defaultBoxColor: '#DDE3EC',
    defaultMetalness: 0.04,
    defaultRoughness: 0.58,
    defaultEmissiveIntensity: 0.0,
    defaultThickness: 0.5,
    cornerRadius: 0.09,
    glowIntensity: 0.0,
    defaultLabelColor: '#1D2A3D',
    defaultSublabelColor: '#5F7088',
    labelSizeFactor: 1.0,
    sublabelSizeFactor: 1.0,
    defaultIconStyle: 'flat',
    defaultSize: [0.15, 0.08] as const,
    defaultIconScale: 0.6,
    defaultIconDepthFactor: 0.5,
    defaultIconDepth: 0.10,
    glowSpread: 2.2,
    sideColorDarkenFactor: -0.08,
    borderColorLightenFactor: 0.15,
    labelFontSizeBase: 0.32,
    sublabelFontSizeBase: 0.22,
    defaultLabelPadding: 0,
    nodeEnvMapIntensity: 0,
  },
  edge: {
    defaultColor: '#4768C9',
    defaultFlowColor: '#2B8EA3',
    defaultFlowSpeed: 0.22,
    defaultFlowWidth: 0.16,
    defaultThickness: 0.055,
    defaultMetalness: 0.06,
    defaultRoughness: 0.62,
    routing: 'flow',
    landing: 'nearest-face',
    smoothness: 1.2,
    use3DArrows: false,
    tubeRadialSegments: 8,
    organicVariation: 1.0,
    flowTurnRadius: 0.035,
    flowFaceStub: 0.05,
    flowBundleStrength: 1.0,
    flowObstaclePadding: 0.025,
    flowTargetApproachBias: 1.35,
    flowUnderpassDepth: 0.08,
    flowUnderpassClearance: 0.03,
    flowTurnPenalty: 0.45,
    flowPunchthroughPenalty: 500,
    flowUnderpassPenalty: 60,
    flowPulseIntensity: 0.26,
  },
  group: {
    defaultColor: '#F1F4F8',
    defaultBorderColor: '#AAB7CA',
    defaultBorderWidth: 1.25,
    defaultBorderHeight: 1.0,
    defaultFillOpacity: 0.40,
    defaultBorderOpacity: 0.65,
    defaultLabelColor: '#1D2A3D',
    borderMetalness: 0.04,
    borderRoughness: 0.65,
    borderSideDarken: 0.55,
    borderEdgeDarken: 0.60,
  },
  environment: {
    envMapUrl: 'none',
    envMapIntensity: 0.04,
    skyColor: '#FFFFFF',
    horizonColor: '#F1F4F8',
  },
  layout: {
    defaultKind: 'grid',
    grid: {
      columns: 'auto',
      spacing: [0.06, 0.06],
      margin: 0,
      groupPadding: 0.035,
      titleGap: 0.025,
      alignment: 'left',
      disconnected: 'next-to',
    },
    hierarchical: {
      direction: 'top-down',
      spacing: [0.045, 0.045],
      margin: 0,
      groupPadding: 0.035,
      titleGap: 0.025,
      alignment: 'center',
      disconnected: 'next-to',
    },
    manual: {
      groupPadding: 0.035,
      titleGap: 0.025,
    },
  },
  palette: ['#3D63D9', '#1E9A6F', '#D64566', '#D2911F', '#7357C7', '#1D93AE', '#A06D2F', '#4E8F3A'],
} as const;
