// lightMinimal DiagramTheme preset — documentation-first clarity with minimal ornament.

import type { DiagramTheme } from '@brewsite/diagram';

export const lightMinimalTheme: DiagramTheme = {
  node: {
    defaultColor: '#F3F6FB',
    defaultBoxColor: '#D6DEE9',
    defaultMetalness: 0.08,
    defaultRoughness: 0.60,
    nodeEnvMapIntensity: 0.0,
    defaultEmissiveIntensity: 0.0,
    defaultThickness: '3u',
    cornerRadius: '1.2%',
    glowIntensity: 0.0,
    defaultLabelColor: '#223248',
    defaultSublabelColor: '#6E7D92',
    labelSizeFactor: 1.0,
    sublabelSizeFactor: 1.0,
    defaultIconStyle: 'flat',
    defaultSize: ['10u', '10u'],
    defaultIconScale: 0.6,
    defaultIconDepth: '3u',
    glowSpread: 2.2,
    defaultBorderColor: '#C4CDD9',
    defaultNodeBorderWidth: '.7u',
    defaultNodeBorderHeight: '.7u',
    labelFontSizeBase: 0.32,
    sublabelFontSizeBase: 0.22,
    defaultLabelPadding: 0,
  },
  edge: {
    defaultColor: '#6A94CD',
    defaultFlowColor: '#67B9C8',
    defaultFlowSpeed: 0.06,
    defaultFlowWidth: 0.18,
    defaultThickness: '.6u',
    defaultMetalness: 0.10,
    defaultRoughness: 0.60,
    routing: 'flow',
    landing: 'nearest-face',
    smoothness: 1.0,
    use3DArrows: false,
    tubeRadialSegments: 8,
    organicVariation: 1.0,
    flowTurnRadius: '3.5%',
    flowFaceStub: '5%',
    flowBundleStrength: 1.0,
    flowObstaclePadding: '2.5%',
    flowTargetApproachBias: 1.35,
    flowTurnPenalty: 0.45,
    flowPunchthroughPenalty: 500,
    flowPulseIntensity: 0.16,
  },
  group: {
    defaultColor: '#E7EDF6',
    defaultBorderColor: '#BFC9D7',
    defaultBorderWidth: '1.5u',
    defaultBorderHeight: '4u',
    defaultFillOpacity: 0.35,
    defaultBorderOpacity: 0.60,
    defaultLabelColor: '#223248',
    borderMetalness: 0.08,
    borderRoughness: 0.60,
    borderSideDarken: 0.70,
    borderEdgeDarken: 0.75,
    defaultBackColor: '#F2F4F8CC',
  },
  environment: {
    envMapUrl: 'none',
    envMapIntensity: 0.0,
    skyColor: '#FFFFFF',
    horizonColor: '#F7F9FC',
  },
  layout: {
    defaultKind: 'grid',
    grid: {
      columns: 'auto',
      spacing: ['6%', '6%'],
      margin: 0,
      groupPadding: '3.5%',
      titleGap: '2.5%',
      alignment: 'left',
      disconnected: 'next-to',
    },
    hierarchical: {
      direction: 'top-down',
      spacing: ['4.5%', '4.5%'],
      margin: 0,
      groupPadding: '3.5%',
      titleGap: '2.5%',
      alignment: 'center',
      disconnected: 'next-to',
    },
    manual: {
      groupPadding: '3.5%',
      titleGap: '2.5%',
    },
  },
  palette: ['#7FAEEA', '#AFA0EA', '#7FD8A2', '#EAA0A0', '#EAD98E', '#78D5E3', '#B9E38C', '#F0C8A2'],
} as const;
