// neonCyber DiagramTheme preset — electric signal language with strict hierarchy.

import type { DiagramTheme } from '@brewsite/diagram';

export const neonCyberTheme: DiagramTheme = {
  node: {
    defaultColor: '#0C183A',
    defaultBoxColor: '#1A3366',
    defaultMetalness: 0.64,
    defaultRoughness: 0.14,
    nodeEnvMapIntensity: 0.18,
    defaultEmissiveIntensity: 0.24,
    defaultThickness: 0.033,
    cornerRadius: 0.006,
    glowIntensity: 0.52,
    defaultLabelColor: '#D8CCFF',
    defaultSublabelColor: '#9688D6',
    labelSizeFactor: 1.0,
    sublabelSizeFactor: 1.0,
    defaultIconStyle: 'extruded',
    defaultSize: [0.15, 0.08] as const,
    defaultIconScale: 0.6,
    defaultIconDepth: 0.15,
    glowSpread: 2.8,
    defaultBorderColor: '#2A4580',
    labelFontSizeBase: 0.32,
    sublabelFontSizeBase: 0.22,
    defaultLabelPadding: 0,
  },
  edge: {
    defaultColor: '#8A3DFF',
    defaultFlowColor: '#00E7FF',
    defaultFlowSpeed: 0.82,
    defaultFlowWidth: 0.16,
    defaultThickness: 0.00825,
    defaultMetalness: 0.68,
    defaultRoughness: 0.14,
    routing: 'flow',
    landing: 'nearest-face',
    smoothness: 1.0,
    use3DArrows: true,
    tubeRadialSegments: 12,
    organicVariation: 2.0,
    flowTurnRadius: 0.035,
    flowFaceStub: 0.05,
    flowBundleStrength: 1.0,
    flowObstaclePadding: 0.025,
    flowTargetApproachBias: 1.35,
    flowUnderpassDepth: 0.08,
    flowUnderpassClearance: 0.03,
    flowTurnPenalty: 0.45,
    flowPunchthroughPenalty: 500,
    flowUnderpassPenalty: 60,
    flowPulseIntensity: 1.0,
  },
  group: {
    defaultColor: '#09122A',
    defaultBorderColor: '#8A3DFF',
    defaultBorderWidth: 0.105,
    defaultBorderHeight: 0.105,
    defaultFillOpacity: 0.07,
    defaultBorderOpacity: 0.80,
    defaultLabelColor: '#D8CCFF',
    borderMetalness: 0.58,
    borderRoughness: 0.20,
    borderSideDarken: 0.35,
    borderEdgeDarken: 0.40,
  },
  environment: {
    envMapUrl: '/assets/envmaps/diagram-default.hdr',
    envMapIntensity: 0.68,
    skyColor: '#02030D',
    horizonColor: '#09122A',
  },
  layout: {
    defaultKind: 'grid',
    grid: {
      columns: 'auto',
      spacing: [0.06, 0.06],
      margin: 0,
      groupPadding: 0.035,
      titleGap: 0.025,
      alignment: 'left',
      disconnected: 'next-to',
    },
    hierarchical: {
      direction: 'top-down',
      spacing: [0.045, 0.045],
      margin: 0,
      groupPadding: 0.035,
      titleGap: 0.025,
      alignment: 'center',
      disconnected: 'next-to',
    },
    manual: {
      groupPadding: 0.035,
      titleGap: 0.025,
    },
  },
  palette: ['#8A3DFF', '#00E7FF', '#C260FF', '#11C9E8', '#5B2CE6', '#5EE8FF', '#A96BFF', '#1AAFD1'],
} as const;
