// Dark Glass theme — deep navy with polished metallic surfaces and subtle node glow.
// This is the package default theme. High visual impact for tech/architecture diagrams.

import type { DiagramTheme } from '../types';

/**
 * Dark Glass: the default diagram theme.
 * Deep navy nodes, polished PBR materials, subtle glow, environment IBL from
 * the bundled Radiance HDR. Optimised for dark-background presentation contexts.
 */
export const darkGlassTheme: DiagramTheme = {
  node: {
    defaultColor:             '#1a2240',
    defaultBoxColor:          '#3a4280',
    defaultMetalness:          0.80,
    defaultRoughness:          0.30,
    defaultEmissiveIntensity:  0.10,
    defaultThickness:          0.58,
    cornerRadius:              0.06,
    glowIntensity:             0.15,
    defaultLabelColor:         '#e8eeff',
    defaultSublabelColor:      '#8ba4d4',
    labelSizeFactor:           1.0,
    sublabelSizeFactor:        1.0,
    defaultIconStyle:          'extruded',
    defaultSize:               [4, 2] as const,
    defaultIconScale:          0.6,
    defaultIconDepthFactor:    0.5,
    defaultIconDepth:          0.15,
    glowSpread:                2.2,
    sideColorDarkenFactor:     -0.15,
    borderColorLightenFactor:  0.25,
    labelFontSizeBase:         0.28,
    sublabelFontSizeBase:      0.18,
  },
  edge: {
    defaultColor:         '#702dc6',
    defaultFlowColor:     '#53ec68',
    defaultFlowSpeed:     0.3,
    defaultFlowWidth:     0.2,
    defaultThickness:     0.065,
    defaultMetalness:     0.50,
    defaultRoughness:     0.30,
    routing:              'flow',
    landing:              'nearest-face',
    smoothness:           1.6,
    use3DArrows:          true,
    tubeRadialSegments:   16,
    organicVariation:     1.6,
    flowTurnRadius:       0.035,
    flowFaceStub:         0.05,
    flowBundleStrength:   .9,
    flowObstaclePadding:  0.025,
    flowTargetApproachBias: 1.35,
    flowUnderpassDepth:   0.08,
    flowUnderpassClearance: 0.03,
    flowTurnPenalty:      0.45,
    flowPunchthroughPenalty: 500,
    flowUnderpassPenalty: 60,
    flowPulseIntensity:   0.9,
  },
  group: {
    defaultColor:         '#ad8176',
    defaultBorderColor:   '#2a4080',
    defaultBorderWidth:   .25,
    defaultBorderHeight:  .7,
    defaultFillOpacity:   0.10,
    defaultBorderOpacity: 0.85,
    defaultLabelColor:    '#ffffff',
    borderMetalness:      0.35,
    borderRoughness:      0.45,
    borderSideDarken:     0.40,
    borderEdgeDarken:     0.45,
  },
  environment: {
    envMapUrl:       '/assets/envmaps/diagram-default.hdr',
    envMapIntensity: 0.9,
    skyColor:        '#1a2a6c',
    horizonColor:    '#0a1030',
  },
  layout: {
    defaultKind: 'grid',
    grid: {
      columns: 'auto',
      spacing: [1, 1],
      margin: 0,
      groupPadding: 1.5,
      titleGap: 1,
      alignment: 'left',
      disconnected: 'next-to',
    },
    hierarchical: {
      direction: 'top-down',
      spacing: [1.5, 1.5],
      margin: 0,
      groupPadding: 1.5,
      titleGap: 1,
      alignment: 'center',
      disconnected: 'next-to',
    },
    manual: {
      groupPadding: 1.5,
      titleGap: 1,
    },
  },
  palette: ['#2a4fa0', '#1e7a5a', '#8a2a70', '#a06a20', '#2a8090'],
} as const;
