// Enterprise theme — board-ready strategic clarity with restrained motion.

// SHARED ACCENT PALETTE — must match packages/charts/src/themes/enterprise.ts
// '#4F76B8', '#3F7F73', '#C9843F', '#6D5D8E', '#3B7E8D', '#8A6C47', '#5A724E', '#8B4A54'

import type { DiagramTheme } from '../types';

export const enterpriseTheme: DiagramTheme = {
  node: {
    defaultColor: '#172029FF',
    defaultBoxColor: '#35587A',
    defaultMetalness: 0.16,
    defaultRoughness: 0.53,
    nodeEnvMapIntensity: 0.08,
    defaultEmissiveIntensity: 0.03,
    defaultThickness: 0.075,
    cornerRadius: 0.0075,
    glowIntensity: 0.0,
    defaultLabelColor: '#E5EEFA',
    defaultSublabelColor: '#A8B8CF',
    labelSizeFactor: 1.0,
    sublabelSizeFactor: 1.0,
    defaultIconStyle: 'flat',
    defaultSize: [0.15, 0.08] as const,
    defaultIconScale: 0.6,
    defaultIconDepth: 0.15,
    glowSpread: 2.2,
    defaultBorderColor: '#4A6B8E',
    defaultNodeBorderWidth: 0.005,
    defaultNodeBorderHeight: 0.005,
    labelFontSizeBase: 0.32,
    sublabelFontSizeBase: 0.22,
    defaultLabelPadding: 0,
  },
  edge: {
    defaultColor: '#4F76B8',
    defaultFlowColor: '#a74dd8',
    defaultFlowSpeed: 0.28,
    defaultFlowWidth: 0.18,
    defaultThickness: 0.0105,
    defaultMetalness: 0.12,
    defaultRoughness: 0.55,
    routing: 'flow',
    landing: 'nearest-face',
    smoothness: 1.0,
    use3DArrows: false,
    tubeRadialSegments: 15,
    organicVariation: 0.8,
    flowTurnRadius: 0.035,
    flowFaceStub: 0.05,

    flowBundleStrength: 1.0,
    flowObstaclePadding: 0.025,
    flowTargetApproachBias: 1.35,
    flowUnderpassDepth: 0.08,
    flowUnderpassClearance: 0.03,
    flowTurnPenalty: 0.45,
    flowPunchthroughPenalty: 500,
    flowUnderpassPenalty: 60,
    flowPulseIntensity: 0.68,
  },
  group: {
    defaultColor: '#15253A',
    defaultBorderColor: '#4A6386',
    defaultBorderWidth: 0.015,
    defaultBorderHeight: 0.105,
    defaultFillOpacity: 0.09,
    defaultBorderOpacity: 0.55,
    defaultLabelColor: '#E5EEFA',
    borderMetalness: 0.12,
    borderRoughness: 0.58,
    borderSideDarken: 0.50,
    borderEdgeDarken: 0.55,
    defaultBackColor: '#1A2838CC',
  },
  environment: {
    envMapUrl: 'none',
    envMapIntensity: 0.55,
    skyColor: '#0A1424',
    horizonColor: '#15253A',
  },
  layout: {
    defaultKind: 'grid',
    grid: {
      columns: 'auto',
      spacing: [0.06, 0.06],
      margin: 0,
      groupPadding: 0.035,
      titleGap: 0.025,
      alignment: 'left',
      disconnected: 'next-to',
    },
    hierarchical: {
      direction: 'top-down',
      spacing: [0.045, 0.045],
      margin: 0,
      groupPadding: 0.035,
      titleGap: 0.025,
      alignment: 'center',
      disconnected: 'next-to',
    },
    manual: {
      groupPadding: 0.035,
      titleGap: 0.025,
    },
  },
  palette: ['#4F76B8', '#3F7F73', '#C9843F', '#6D5D8E', '#3B7E8D', '#8A6C47', '#5A724E', '#8B4A54'],
} as const;

/** Default DiagramTheme — enterprise aesthetic. Used as the pre-loaded registry fallback. */
export const defaultDiagramTheme: DiagramTheme = enterpriseTheme;
