// Enterprise theme — polished slate-blue, professional matte, no glow, no flow.
// Board-ready: data matters, not presentation effects.

// SHARED ACCENT PALETTE — must match packages/charts/src/themes/enterprise.ts
// Index 0–4: diagram node palette[0..4]; indices 0–7: chart series[0..7].color
// '#3a5fa0', '#38766a', '#c87830', '#5a4e7a', '#2e7280', '#7a5c38', '#456040', '#7a3840'

import type { DiagramTheme } from '../types';

export const enterpriseTheme: DiagramTheme = {
  node: {
    defaultColor:             '#182844',
    defaultBoxColor:          '#243d60',
    defaultMetalness:          0.16,
    defaultRoughness:          0.53,
    defaultEmissiveIntensity:  0.04,
    defaultThickness:          0.32,
    cornerRadius:              0.05,
    glowIntensity:             0.0,
    defaultLabelColor:         '#e8f0ff',
    defaultSublabelColor:      '#8898c0',
    labelSizeFactor:           1.0,
    sublabelSizeFactor:        1.0,
    defaultIconStyle:          'flat',
    defaultSize:               [4, 2] as const,
    defaultIconScale:          0.6,
    defaultIconDepthFactor:    0.5,
    defaultIconDepth:          0.15,
    glowSpread:                2.2,
    sideColorDarkenFactor:     -0.15,
    borderColorLightenFactor:  0.25,
    labelFontSizeBase:         0.28,
    sublabelFontSizeBase:      0.18,
  },
  edge: {
    defaultColor:               '#3a6aaa',
    defaultFlowSpeed:            0.0,
    defaultFlowWidth:            0.18,
    defaultThickness:            0.070,
    defaultMetalness:            0.12,
    defaultRoughness:            0.55,
    routing:                    'flow',
    landing:                    'nearest-face',
    smoothness:                  1.0,
    use3DArrows:                 false,
    tubeRadialSegments:          8,
    organicVariation:            0.8,
    flowTurnRadius:              0.035,
    flowFaceStub:                0.05,
    flowBundleStrength:          1.0,
    flowObstaclePadding:         0.025,
    flowTargetApproachBias:      1.35,
    flowUnderpassDepth:          0.08,
    flowUnderpassClearance:      0.03,
    flowTurnPenalty:             0.45,
    flowPunchthroughPenalty:     500,
    flowUnderpassPenalty:        60,
    flowPulseIntensity:          0.9,
  },
  group: {
    defaultColor:         '#0f1e38',
    defaultBorderColor:   '#243d60',
    defaultBorderWidth:    1.25,
    defaultBorderHeight:   1.0,
    defaultFillOpacity:    0.09,
    defaultBorderOpacity:  0.55,
    defaultLabelColor:    '#e8f0ff',
    borderMetalness:       0.12,
    borderRoughness:       0.58,
    borderSideDarken:      0.50,
    borderEdgeDarken:      0.55,
  },
  environment: {
    envMapUrl:       '/assets/envmaps/diagram-default.hdr',
    envMapIntensity:  0.75,
    skyColor:        '#0a1828',
    horizonColor:    '#182840',
  },
  layout: {
    defaultKind: 'grid',
    grid: {
      columns: 'auto',
      spacing: [2, 2],
      margin: 0,
      groupPadding: 1.5,
      titleGap: 0.75,
      alignment: 'left',
      disconnected: 'next-to',
    },
    hierarchical: {
      direction: 'top-down',
      spacing: [1.5, 1.5],
      margin: 0,
      groupPadding: 1.5,
      titleGap: 0.75,
      alignment: 'center',
      disconnected: 'next-to',
    },
    manual: {
      groupPadding: 1.5,
      titleGap: 0.75,
    },
  },
  palette: ['#3a5fa0', '#38766a', '#c87830', '#5a4e7a', '#2e7280'],
} as const;
