// Light Canvas theme — white ceramic nodes, warm neutral background, jewel-tone accents.
// Premium light theme: physical depth and visual richness without IBL reflections.

// SHARED ACCENT PALETTE — must match packages/charts/src/themes/lightCanvas.ts
// Index 0–4: diagram node palette[0..4]; indices 0–7: chart series[0..7].color
// '#3355cc', '#1a9966', '#cc3355', '#cc8800', '#6644bb', '#0088aa', '#996622', '#448822'

import type { DiagramTheme } from '../types';

export const lightCanvasTheme: DiagramTheme = {
  node: {
    defaultColor:             '#ffffff',
    defaultBoxColor:          '#f0f4fa',
    defaultMetalness:          0.04,
    defaultRoughness:          0.58,
    defaultEmissiveIntensity:  0.0,
    defaultThickness:          0.20,
    cornerRadius:              0.09,
    glowIntensity:             0.0,
    defaultLabelColor:         '#18202c',
    defaultSublabelColor:      '#4a5a80',
    labelSizeFactor:           1.0,
    sublabelSizeFactor:        1.0,
    defaultIconStyle:          'flat',
    defaultSize:               [4, 2] as const,
    defaultIconScale:          0.6,
    defaultIconDepthFactor:    0.5,
    defaultIconDepth:          0.10,
    glowSpread:                2.2,
    sideColorDarkenFactor:     -0.08,
    borderColorLightenFactor:  0.15,
    labelFontSizeBase:         0.28,
    sublabelFontSizeBase:      0.18,
  },
  edge: {
    defaultColor:               '#3a5fa8',
    defaultFlowColor:           '#1a5fd8',
    defaultFlowSpeed:            0.6,
    defaultFlowWidth:            0.16,
    defaultThickness:            0.055,
    defaultMetalness:            0.06,
    defaultRoughness:            0.62,
    routing:                    'flow',
    landing:                    'nearest-face',
    smoothness:                  1.2,
    use3DArrows:                 false,
    tubeRadialSegments:          8,
    organicVariation:            1.0,
    flowTurnRadius:              0.035,
    flowFaceStub:                0.05,
    flowBundleStrength:          1.0,
    flowObstaclePadding:         0.025,
    flowTargetApproachBias:      1.35,
    flowUnderpassDepth:          0.08,
    flowUnderpassClearance:      0.03,
    flowTurnPenalty:             0.45,
    flowPunchthroughPenalty:     500,
    flowUnderpassPenalty:        60,
    flowPulseIntensity:          0.85,
  },
  group: {
    defaultColor:         '#e8edf6',
    defaultBorderColor:   '#b8c5dc',
    defaultBorderWidth:    1.25,
    defaultBorderHeight:   1.0,
    defaultFillOpacity:    0.40,
    defaultBorderOpacity:  0.65,
    defaultLabelColor:    '#18202c',
    borderMetalness:       0.04,
    borderRoughness:       0.65,
    borderSideDarken:      0.55,
    borderEdgeDarken:      0.60,
  },
  environment: {
    envMapUrl:       'none',
    envMapIntensity:  0,
    skyColor:        '#ffffff',
    horizonColor:    '#e0e8f8',
  },
  layout: {
    defaultKind: 'grid',
    grid: {
      columns: 'auto',
      spacing: [2, 2],
      margin: 0,
      groupPadding: 1.5,
      titleGap: 0.75,
      alignment: 'left',
      disconnected: 'next-to',
    },
    hierarchical: {
      direction: 'top-down',
      spacing: [1.5, 1.5],
      margin: 0,
      groupPadding: 1.5,
      titleGap: 0.75,
      alignment: 'center',
      disconnected: 'next-to',
    },
    manual: {
      groupPadding: 1.5,
      titleGap: 0.75,
    },
  },
  palette: ['#3355cc', '#1a9966', '#cc3355', '#cc8800', '#6644bb'],
} as const;
