// @internal — not part of the public API. Use @brewsite/themes bundles instead.
// Light Minimal theme — documentation-first clarity with minimal ornament.

// SHARED ACCENT PALETTE — must match packages/charts/src/themes/lightMinimal.ts
// '#7FAEEA', '#AFA0EA', '#7FD8A2', '#EAA0A0', '#EAD98E', '#78D5E3', '#B9E38C', '#F0C8A2'

import type { DiagramTheme } from '../types';

export const lightMinimalTheme: DiagramTheme = {
  node: {
    defaultColor: '#F3F6FB',
    defaultBoxColor: '#D6DEE9',
    defaultMetalness: 0.08,
    defaultRoughness: 0.60,
    nodeEnvMapIntensity: 0.0,
    defaultEmissiveIntensity: 0.0,
    defaultThickness: 0.30,
    cornerRadius: 0.08,
    glowIntensity: 0.0,
    defaultLabelColor: '#223248',
    defaultSublabelColor: '#6E7D92',
    labelSizeFactor: 1.0,
    sublabelSizeFactor: 1.0,
    defaultIconStyle: 'flat',
    defaultSize: [4, 2] as const,
    defaultIconScale: 0.6,
    defaultIconDepthFactor: 0.5,
    defaultIconDepth: 0.10,
    glowSpread: 2.2,
    sideColorDarkenFactor: -0.10,
    borderColorLightenFactor: 0.20,
    labelFontSizeBase: 0.28,
    sublabelFontSizeBase: 0.18,
    defaultLabelPadding: 0,
  },
  edge: {
    defaultColor: '#6A94CD',
    defaultFlowColor: '#67B9C8',
    defaultFlowSpeed: 0.06,
    defaultFlowWidth: 0.18,
    defaultThickness: 0.060,
    defaultMetalness: 0.10,
    defaultRoughness: 0.60,
    routing: 'flow',
    landing: 'nearest-face',
    smoothness: 1.0,
    use3DArrows: false,
    tubeRadialSegments: 8,
    organicVariation: 1.0,
    flowTurnRadius: 0.035,
    flowFaceStub: 0.05,
    flowBundleStrength: 1.0,
    flowObstaclePadding: 0.025,
    flowTargetApproachBias: 1.35,
    flowUnderpassDepth: 0.08,
    flowUnderpassClearance: 0.03,
    flowTurnPenalty: 0.45,
    flowPunchthroughPenalty: 500,
    flowUnderpassPenalty: 60,
    flowPulseIntensity: 0.16,
  },
  group: {
    defaultColor: '#E7EDF6',
    defaultBorderColor: '#BFC9D7',
    defaultBorderWidth: 1.25,
    defaultBorderHeight: 1.0,
    defaultFillOpacity: 0.35,
    defaultBorderOpacity: 0.60,
    defaultLabelColor: '#223248',
    borderMetalness: 0.08,
    borderRoughness: 0.60,
    borderSideDarken: 0.70,
    borderEdgeDarken: 0.75,
  },
  environment: {
    envMapUrl: 'none',
    envMapIntensity: 0.0,
    skyColor: '#FFFFFF',
    horizonColor: '#F7F9FC',
  },
  layout: {
    defaultKind: 'grid',
    grid: {
      columns: 'auto',
      spacing: [2, 2],
      margin: 0,
      groupPadding: 1.5,
      titleGap: 0.75,
      alignment: 'left',
      disconnected: 'next-to',
    },
    hierarchical: {
      direction: 'top-down',
      spacing: [1.5, 1.5],
      margin: 0,
      groupPadding: 1.5,
      titleGap: 0.75,
      alignment: 'center',
      disconnected: 'next-to',
    },
    manual: {
      groupPadding: 1.5,
      titleGap: 0.75,
    },
  },
  palette: ['#7FAEEA', '#AFA0EA', '#7FD8A2', '#EAA0A0', '#EAD98E', '#78D5E3', '#B9E38C', '#F0C8A2'],
} as const;
