// @internal — not part of the public API. Use @brewsite/themes bundles instead.
// Light Canvas theme — premium editorial light mode with controlled jewel accents.

// SHARED ACCENT PALETTE — must match packages/charts/src/themes/lightCanvas.ts
// '#3D63D9', '#1E9A6F', '#D64566', '#D2911F', '#7357C7', '#1D93AE', '#A06D2F', '#4E8F3A'

import type { DiagramTheme } from '../types';

export const lightCanvasTheme: DiagramTheme = {
  node: {
    defaultColor: '#FFFFFF',
    defaultBoxColor: '#DDE3EC',
    defaultMetalness: 0.04,
    defaultRoughness: 0.58,
    defaultEmissiveIntensity: 0.0,
    defaultThickness: '4u',
    cornerRadius: '1.35%',
    glowIntensity: 0.0,
    defaultLabelColor: '#1D2A3D',
    defaultSublabelColor: '#5F7088',
    labelSizeFactor: 1.0,
    sublabelSizeFactor: 1.0,
    defaultIconStyle: 'flat',
    defaultSize: ['10u', '10u'],
    defaultIconScale: 0.6,
    defaultIconDepth: '3u',
    glowSpread: 2.2,
    defaultBorderColor: '#C8D0DC',
    defaultNodeBorderWidth: '.7u',
    defaultNodeBorderHeight: '.7u',
    labelFontSizeBase: 0.32,
    sublabelFontSizeBase: 0.22,
    defaultLabelPadding: 0,
    nodeEnvMapIntensity: 0,
  },
  edge: {
    defaultColor: '#4768C9',
    defaultFlowColor: '#2B8EA3',
    defaultFlowSpeed: 0.22,
    defaultFlowWidth: 0.16,
    defaultThickness: '.6u',
    defaultMetalness: 0.06,
    defaultRoughness: 0.62,
    routing: 'flow',
    landing: 'nearest-face',
    smoothness: 1.2,
    use3DArrows: false,
    tubeRadialSegments: 8,
    organicVariation: 1.0,
    flowTurnRadius: '3.5%',
    flowFaceStub: '5%',
    flowBundleStrength: 1.0,
    flowObstaclePadding: '2.5%',
    flowTargetApproachBias: 1.35,
    flowTurnPenalty: 0.45,
    flowPunchthroughPenalty: 500,
    flowPulseIntensity: 0.26,
  },
  group: {
    defaultColor: '#F1F4F8',
    defaultBorderColor: '#AAB7CA',
    defaultBorderWidth: '1.5u',
    defaultBorderHeight: '4u',
    defaultFillOpacity: 0.40,
    defaultBorderOpacity: 0.65,
    defaultLabelColor: '#1D2A3D',
    borderMetalness: 0.04,
    borderRoughness: 0.65,
    borderSideDarken: 0.55,
    borderEdgeDarken: 0.60,
    defaultBackColor: '#F0F4F0CC',
  },
  environment: {
    envMapUrl: 'none',
    envMapIntensity: 0.04,
    skyColor: '#FFFFFF',
    horizonColor: '#F1F4F8',
  },
  layout: {
    defaultKind: 'grid',
    grid: {
      columns: 'auto',
      spacing: ['6%', '6%'],
      margin: 0,
      groupPadding: '3.5%',
      titleGap: '2.5%',
      alignment: 'left',
      disconnected: 'next-to',
    },
    hierarchical: {
      direction: 'top-down',
      spacing: ['4.5%', '4.5%'],
      margin: 0,
      groupPadding: '3.5%',
      titleGap: '2.5%',
      alignment: 'center',
      disconnected: 'next-to',
    },
    manual: {
      groupPadding: '3.5%',
      titleGap: '2.5%',
    },
  },
  palette: ['#3D63D9', '#1E9A6F', '#D64566', '#D2911F', '#7357C7', '#1D93AE', '#A06D2F', '#4E8F3A'],
} as const;
