// @internal — not part of the public API. Use @brewsite/themes bundles instead.
// Midnight theme — warm cinematic tone with bronze/amber authority.

// SHARED ACCENT PALETTE — must match packages/charts/src/themes/midnight.ts
// '#E2A33A', '#D0634B', '#C39B52', '#4F8D7B', '#A86A8F', '#8B6A3D', '#6B8446', '#BE6B4A'

import type { DiagramTheme } from '../types';

export const midnightTheme: DiagramTheme = {
  node: {
    defaultColor: '#261A13',
    defaultBoxColor: '#3D2E22',
    defaultMetalness: 0.28,
    defaultRoughness: 0.50,
    defaultEmissiveIntensity: 0.05,
    defaultThickness: 0.210,
    cornerRadius: 0.009,
    glowIntensity: 0.0,
    defaultLabelColor: '#F2E7D4',
    defaultSublabelColor: '#BCA180',
    labelSizeFactor: 1.0,
    sublabelSizeFactor: 1.0,
    defaultIconStyle: 'extruded',
    defaultSize: [0.15, 0.08] as const,
    defaultIconScale: 0.6,
    defaultIconDepthFactor: 0.5,
    defaultIconDepth: 0.15,
    glowSpread: 2.2,
    sideColorDarkenFactor: -0.15,
    borderColorLightenFactor: 0.20,
    labelFontSizeBase: 0.32,
    sublabelFontSizeBase: 0.22,
    defaultLabelPadding: 0,
    nodeEnvMapIntensity: 0.15,
  },
  edge: {
    defaultColor: '#E2A33A',
    defaultFlowColor: '#D0634B',
    defaultFlowSpeed: 0.24,
    defaultFlowWidth: 0.18,
    defaultThickness: 0.009,
    defaultMetalness: 0.34,
    defaultRoughness: 0.52,
    routing: 'flow',
    landing: 'nearest-face',
    smoothness: 1.3,
    use3DArrows: true,
    tubeRadialSegments: 12,
    organicVariation: 1.3,
    flowTurnRadius: 0.035,
    flowFaceStub: 0.05,
    flowBundleStrength: 0.9,
    flowObstaclePadding: 0.025,
    flowTargetApproachBias: 1.35,
    flowUnderpassDepth: 0.08,
    flowUnderpassClearance: 0.03,
    flowTurnPenalty: 0.45,
    flowPunchthroughPenalty: 500,
    flowUnderpassPenalty: 60,
    flowPulseIntensity: 0.58,
  },
  group: {
    defaultColor: '#1A120D',
    defaultBorderColor: '#7D603C',
    defaultBorderWidth: 0.015,
    defaultBorderHeight: 0.105,
    defaultFillOpacity: 0.12,
    defaultBorderOpacity: 0.80,
    defaultLabelColor: '#F2E7D4',
    borderMetalness: 0.26,
    borderRoughness: 0.54,
    borderSideDarken: 0.45,
    borderEdgeDarken: 0.50,
  },
  environment: {
    envMapUrl: 'none',
    envMapIntensity: 0.55,
    skyColor: '#1A120D',
    horizonColor: '#332319',
  },
  layout: {
    defaultKind: 'grid',
    grid: {
      columns: 'auto',
      spacing: [0.05, 0.05],
      margin: 0,
      groupPadding: 0.035,
      titleGap: 0.03,
      alignment: 'left',
      disconnected: 'next-to',
    },
    hierarchical: {
      direction: 'top-down',
      spacing: [0.045, 0.045],
      margin: 0,
      groupPadding: 0.035,
      titleGap: 0.03,
      alignment: 'center',
      disconnected: 'next-to',
    },
    manual: {
      groupPadding: 0.035,
      titleGap: 0.03,
    },
  },
  palette: ['#E2A33A', '#D0634B', '#C39B52', '#4F8D7B', '#A86A8F', '#8B6A3D', '#6B8446', '#BE6B4A'],
} as const;
