// Neon Cyber theme — electric violet + laser cyan, high emissive, structured circuit look.

// SHARED ACCENT PALETTE — must match packages/charts/src/themes/neonCyber.ts
// Index 0–4: diagram node palette[0..4]; indices 0–7: chart series[0..7].color
// '#7b2dff', '#00eeff', '#b855ff', '#00ccdd', '#5020cc', '#44ddee', '#9944ff', '#00aacc'

import type { DiagramTheme } from '../types';

export const neonCyberTheme: DiagramTheme = {
  node: {
    defaultColor:             '#060b1a',
    defaultBoxColor:          '#0e1530',
    defaultMetalness:          0.65,
    defaultRoughness:          0.14,
    defaultEmissiveIntensity:  0.28,
    defaultThickness:          0.22,
    cornerRadius:              0.04,
    glowIntensity:             0.60,
    defaultLabelColor:         '#b090ff',
    defaultSublabelColor:      '#8068cc',
    labelSizeFactor:           1.0,
    sublabelSizeFactor:        1.0,
    defaultIconStyle:          'extruded',
    defaultSize:               [4, 2] as const,
    defaultIconScale:          0.6,
    defaultIconDepthFactor:    0.5,
    defaultIconDepth:          0.15,
    glowSpread:                2.8,
    sideColorDarkenFactor:     -0.15,
    borderColorLightenFactor:  0.25,
    labelFontSizeBase:         0.28,
    sublabelFontSizeBase:      0.18,
  },
  edge: {
    defaultColor:               '#7b2dff',
    defaultFlowColor:           '#00eeff',
    defaultFlowSpeed:            0.8,
    defaultFlowWidth:            0.16,
    defaultThickness:            0.055,
    defaultMetalness:            0.70,
    defaultRoughness:            0.12,
    routing:                    'flow',
    landing:                    'nearest-face',
    smoothness:                  1.0,
    use3DArrows:                 true,
    tubeRadialSegments:          12,
    organicVariation:            2.0,
    flowTurnRadius:              0.035,
    flowFaceStub:                0.05,
    flowBundleStrength:          1.0,
    flowObstaclePadding:         0.025,
    flowTargetApproachBias:      1.35,
    flowUnderpassDepth:          0.08,
    flowUnderpassClearance:      0.03,
    flowTurnPenalty:             0.45,
    flowPunchthroughPenalty:     500,
    flowUnderpassPenalty:        60,
    flowPulseIntensity:          0.95,
  },
  group: {
    defaultColor:         '#050810',
    defaultBorderColor:   '#7b2dff',
    defaultBorderWidth:    1.75,
    defaultBorderHeight:   1.0,
    defaultFillOpacity:    0.07,
    defaultBorderOpacity:  0.80,
    defaultLabelColor:    '#b090ff',
    borderMetalness:       0.60,
    borderRoughness:       0.18,
    borderSideDarken:      0.35,
    borderEdgeDarken:      0.40,
  },
  environment: {
    envMapUrl:       '/assets/envmaps/diagram-default.hdr',
    envMapIntensity:  0.6,
    skyColor:        '#010310',
    horizonColor:    '#06102a',
  },
  layout: {
    defaultKind: 'grid',
    grid: {
      columns: 'auto',
      spacing: [2, 2],
      margin: 0,
      groupPadding: 1.5,
      titleGap: 0.75,
      alignment: 'left',
      disconnected: 'next-to',
    },
    hierarchical: {
      direction: 'top-down',
      spacing: [1.5, 1.5],
      margin: 0,
      groupPadding: 1.5,
      titleGap: 0.75,
      alignment: 'center',
      disconnected: 'next-to',
    },
    manual: {
      groupPadding: 1.5,
      titleGap: 0.75,
    },
  },
  palette: ['#7b2dff', '#00eeff', '#b855ff', '#00ccdd', '#5020cc'],
} as const;
