// @internal — not part of the public API. Use @brewsite/themes bundles instead.
// Neon Cyber theme — electric signal language with strict hierarchy.

// SHARED ACCENT PALETTE — must match packages/charts/src/themes/neonCyber.ts
// '#8A3DFF', '#00E7FF', '#C260FF', '#11C9E8', '#5B2CE6', '#5EE8FF', '#A96BFF', '#1AAFD1'

import type { DiagramTheme } from '../types';

export const neonCyberTheme: DiagramTheme = {
  node: {
    defaultColor: '#0C183A',
    defaultBoxColor: '#1A3366',
    defaultMetalness: 0.64,
    defaultRoughness: 0.14,
    nodeEnvMapIntensity: 0.18,
    defaultEmissiveIntensity: 0.24,
    defaultThickness: '3u',
    cornerRadius: '0.6%',
    glowIntensity: 0.52,
    defaultLabelColor: '#D8CCFF',
    defaultSublabelColor: '#9688D6',
    labelSizeFactor: 1.0,
    sublabelSizeFactor: 1.0,
    defaultIconStyle: 'extruded',
    defaultSize: ['10u', '10u'],
    defaultIconScale: 0.6,
    defaultIconDepth: '3u',
    glowSpread: 2.8,
    defaultBorderColor: '#2A4580',
    defaultNodeBorderWidth: '.7u',
    defaultNodeBorderHeight: '.7u',
    labelFontSizeBase: 0.32,
    sublabelFontSizeBase: 0.22,
    defaultLabelPadding: 0,
  },
  edge: {
    defaultColor: '#8A3DFF',
    defaultFlowColor: '#00E7FF',
    defaultFlowSpeed: 0.82,
    defaultFlowWidth: 0.16,
    defaultThickness: '.6u',
    defaultMetalness: 0.68,
    defaultRoughness: 0.14,
    routing: 'flow',
    landing: 'nearest-face',
    smoothness: 1.0,
    use3DArrows: true,
    tubeRadialSegments: 12,
    organicVariation: 2.0,
    flowTurnRadius: '3.5%',
    flowFaceStub: '5%',
    flowBundleStrength: 1.0,
    flowObstaclePadding: '2.5%',
    flowTargetApproachBias: 1.35,
    flowTurnPenalty: 0.45,
    flowPunchthroughPenalty: 500,
    flowPulseIntensity: 1.0,
  },
  group: {
    defaultColor: '#09122A',
    defaultBorderColor: '#8A3DFF',
    defaultBorderWidth: '1.5u',
    defaultBorderHeight: '4u',
    defaultFillOpacity: 0.07,
    defaultBorderOpacity: 0.80,
    defaultLabelColor: '#D8CCFF',
    borderMetalness: 0.58,
    borderRoughness: 0.20,
    borderSideDarken: 0.35,
    borderEdgeDarken: 0.40,
    defaultBackColor: '#0C1428CC',
  },
  environment: {
    envMapUrl: 'none',
    envMapIntensity: 0.68,
    skyColor: '#02030D',
    horizonColor: '#09122A',
  },
  layout: {
    defaultKind: 'grid',
    grid: {
      columns: 'auto',
      spacing: ['6%', '6%'],
      margin: 0,
      groupPadding: '3.5%',
      titleGap: '2.5%',
      alignment: 'left',
      disconnected: 'next-to',
    },
    hierarchical: {
      direction: 'top-down',
      spacing: ['4.5%', '4.5%'],
      margin: 0,
      groupPadding: '3.5%',
      titleGap: '2.5%',
      alignment: 'center',
      disconnected: 'next-to',
    },
    manual: {
      groupPadding: '3.5%',
      titleGap: '2.5%',
    },
  },
  palette: ['#8A3DFF', '#00E7FF', '#C260FF', '#11C9E8', '#5B2CE6', '#5EE8FF', '#A96BFF', '#1AAFD1'],
} as const;
