// Material preset and application types — shared across all packages.

/**
 * Texture map URLs for a single PBR material preset.
 * All URLs point to .ktx2 files served from the consumer's static directory.
 * Paths are relative to a configured basePath (e.g. '/assets/materials').
 */
export type MaterialPresetMaps = {
  readonly color: string;
  readonly normal: string;
  readonly roughness: string;
  readonly metalness?: string;
  readonly displacement?: string;
};

/**
 * PBR parameter defaults that accompany a material preset.
 * Applied when the material is loaded; overridden by widget-specific style props.
 */
export type MaterialPresetDefaults = {
  readonly metalness: number;
  readonly roughness: number;
};

/**
 * A named material preset: texture URLs + PBR defaults.
 * Resolved from the MaterialManifest at runtime.
 */
export type MaterialPreset = {
  readonly maps: MaterialPresetMaps;
  readonly defaults: MaterialPresetDefaults;
};

/**
 * Manifest mapping preset names to their texture URLs and defaults.
 * Generated by the @brewsite/textures package and registered on
 * WidgetRegistry via texturesPlugin().
 */
export type MaterialManifest = {
  readonly version: number;
  readonly basePath: string;
  readonly presets: Readonly<Record<string, MaterialPreset>>;
};

/**
 * Controls how a material preset's textures are applied to a surface.
 *
 * These are application-time knobs — they modify how the preset's raw
 * textures blend onto the geometry, not the textures themselves. The same
 * 'onyx' preset can look subtle (low colorMix, desaturated) behind text
 * or vivid (full colorMix, saturated) on an empty floor.
 *
 * All values default to "full strength, no adjustment" when omitted.
 * All numeric values are uniform-only updates — O(1), no GPU recompile,
 * safe to call every frame, animatable through the transition system.
 */
export type MaterialApplication = {
  /**
   * How much the texture color replaces the base color [0-1].
   * 0 = pure base color (texture invisible). 1 = pure texture color.
   * Primary readability dial — lower when text sits on the surface.
   * @default 1.0
   */
  readonly colorMix?: number;

  /**
   * Texture brightness multiplier [0-2+].
   * 1.0 = unchanged. <1 = darker. >1 = brighter.
   * @default 1.0
   */
  readonly brightness?: number;

  /**
   * Texture saturation multiplier [0-2+].
   * 0 = fully desaturated (grayscale). 1.0 = unchanged. >1 = oversaturated.
   * @default 1.0
   */
  readonly saturation?: number;

  /**
   * Texture contrast adjustment [-1 to 1].
   * 0 = unchanged. >0 = more contrast. <0 = flatter/washed out.
   * @default 0
   */
  readonly contrast?: number;

  /**
   * How much the texture's normal/bump detail shows [0-1].
   * 0 = flat surface (no depth). 1 = full depth detail.
   * @default 1.0
   */
  readonly depthMix?: number;

  /**
   * How much the texture's roughness map overrides base roughness [0-1].
   * 0 = uniform base roughness. 1 = full texture roughness variation.
   * @default 1.0
   */
  readonly roughnessMix?: number;

  /**
   * Tint color multiplied into the texture color before mixing.
   * Colorize neutral stone/metal to match a brand palette.
   * @default undefined (no tint)
   */
  readonly tint?: string;

  /**
   * Texture coordinate scale override. Larger = fewer repeats (zoomed in).
   * @default undefined (use preset default, typically 0.12)
   */
  readonly texScale?: number;

  /**
   * Thin-film iridescence strength [0-1].
   * Simulates oil-slick / anodized metal / pearl sheen.
   * Auto-upgrades CSM base to MeshPhysicalMaterial when > 0.
   * @default 0
   */
  readonly iridescence?: number;

  /**
   * Iridescence film refractive index [1.0-2.33].
   * Lower = broad soft shifts (soap bubble). Higher = tight vivid bands (bismuth).
   * @default 1.3
   */
  readonly iridescenceIOR?: number;

  /**
   * Thin-film thickness range in nanometers [min, max].
   * Controls which colors appear. [100,200]=cool blues. [200,400]=full rainbow. [300,500]=warm golds.
   * @default [100, 400]
   */
  readonly iridescenceThicknessRange?: readonly [number, number];
};

/**
 * Loaded texture set — Three.js Texture objects ready to apply.
 * Returned by MaterialLoader.loadPreset().
 */
export type LoadedMaterialTextures = {
  readonly color: import('three').Texture;
  readonly normal: import('three').Texture;
  readonly roughness: import('three').Texture;
  readonly metalness?: import('three').Texture;
  readonly displacement?: import('three').Texture;
};

/**
 * Resolved preset with loaded GPU textures + PBR defaults.
 */
export type LoadedMaterialPreset = {
  readonly textures: LoadedMaterialTextures;
  readonly defaults: MaterialPresetDefaults;
};
